# # External Load Balancer is below
apiVersion: v1
kind: Service
metadata:
  labels:
    name: helmmongodb
  name: helmmongodb-ext
spec:
  type: LoadBalancer
  ports:
    - port: 27017
  selector:
    statefulset.kubernetes.io/pod-name: helmmongodb-0


