mongodb:
  uri:"mongodb://mongodb-0.mongo.mongo.svc.cluster.local:27017,mongodb-1.mongo.mongo.svc.cluster.local:27017,mongodb-2.mongo.mongo.svc.cluster.local:27017/?replicaSet=rs0"
image:
  repository: harbor.s.com/mongo/mongodb-exporter
  tag: 0.7.0